### ISSUE TITLE
Error encountered when calculating coastal change rates in Coastal Erosion Real World Example

### ISSUE THREAD

**Issue by mariarodriguezn** [GeoscienceAustralia/dea-notebooks#1063]
Hello,

I encountered an issue while working on the Coastal Erosion Real World Example in the Digital Earth Australia Sandbox. After doing all the recommended steps, I attempted to calculate the rates of coastal change, similar to the same example provided for Africa. However, when running the annual_movements function, I consistently encountered the error message "TypeError: No matching signature match," despite correctly setting the input parameter data types.

To resolve this problem, it was necessary to change the data type of the "MNDWI" values in the "landsat_summaries" dataset from float32 to float64:
```python
landsat_summaries["MNDWI"] = landsat_summaries["MNDWI"].astype("float64")
```
Thank you

**Comment by robbibt** [comment]
Thanks so much for this @mariarodriguezn! This turns out to be a bug with `scipy` version 1.10: https://github.com/scipy/scipy/issues/17718

We'll update the package on the DEA Sandbox and hopefully that will resolve it. For now, you can temporarily work around the issue by upgrading `scipy` before running your analysis:
```
!pip install scipy==1.10.1
```

**Comment by robbibt** [comment]
Hey @mariarodriguezn, we've now updated scipy in the DEA Sandbox, so this should work fine now.

Closing this issue for now, but let us know if you still have problems!
