### ISSUE TITLE
Bulk update notebook info sections (related to #186)

### ISSUE THREAD

**Issue by BexDunn** [GeoscienceAustralia/dea-notebooks#263]
suggest updating to something similar to the following?

`This notebook assumes you have cloned or downloaded a copy of the latest version of the dea-notebooks repository by following the instructions on [DEA notebooks using command line git](https://github.com/GeoscienceAustralia/dea-notebooks#dea-notebooks-using-command-line-git) or [DEA notebooks using Github](https://github.com/GeoscienceAustralia/dea-notebooks#dea-notebooks-using-github). If you didn't, you will need to download any scripts that fail in the first cell into your relative directory so that the notebook will have access to those scripts (`"../"` means the directory above your current directory).`

**Comment by robbibt** [comment]
@BexDunn Very minor update to the above for future updates (no need to update the already done ones):

"This notebook assumes you have **cloned or downloaded a copy of the latest version** of the dea-notebooks repository by following the instructions on [DEA notebooks using command line git](https://github.com/GeoscienceAustralia/dea-notebooks#dea-notebooks-using-command-line-git) or [DEA notebooks using Github](https://github.com/GeoscienceAustralia/dea-notebooks#dea-notebooks-using-github). If you didn't, you will need to download any scripts that fail in the first cell into your relative directory so that the notebook will have access to those scripts ("../" means the directory above your current directory)"
