### ISSUE TITLE
Convert Scripts folder into package

### ISSUE THREAD

**Issue by s-m-t-c** [GeoscienceAustralia/dea-notebooks#538]
We should convert `Scripts `into a separate package for:
* Simplified development process due to de-duplication with [deafrica-sandbox-notebooks](https://github.com/digitalearthafrica/deafrica-sandbox-notebooks)
* Testing
* Reduces path related import issues.
* Refocusing of `Dea-notebooks` and related repos to primarily hold just notebooks.

**Todo**:
* Decide if any functions / `.py` files aren't suitable for this transition
* Write `setup.py` etc
* Write tests
* Modify existing notebooks to import from package

**Comment by robbibt** [comment]
This issue will definitely overlap with and contribute to some of the issues discussed in #507, too

**Comment by benjimin** [comment]
My thoughts:

- Should be an **odc-contrib** repo. It is not DEA specific (sharing with Africa is a primary motivation). It is more of an incubator, for ODC _users_ to submit things that might eventually be folded into more-stable ODC core libraries (but perhaps sharing at a still experimental stage).

- Great candidate for _continuous deployment_ so that users workflows are not unduly interrupted. For example I may organise my notebook to have a function, initially move it into a co-located script, then want to paste it amongst the shared scripts, and don't want to have to wait weeks/months before I can update my notebook's import statements (and purge my initial co-located script), otherwise the versioning/synchronisation issues will likely remain. Is there a python auto-update library, that we (or at least the admins on each of our environments) can use to poll for new commits on github (that travis will have already vetted for import errors) and if so pull the updates (this seems more practical to me than configuring the common repo with hooks for every single platform where it is used)?

**Comment by robbibt** [comment]
Quick audit of the `Scripts` folder: I think all of the `dea_*` prefixed modules are probably candidates for inclusion in a Python package... the `notebook_app*` ones are less re-usable and can probably still be hosted in `dea-notebooks`:

- dea_bandindices.py
- dea_bom.py
- dea_classificationtools.py
- dea_coastaltools.py
- dea_dask.py
- dea_datahandling.py
- dea_plotting.py
- dea_spatialtools.py
- dea_temporaltools.py

**Comment by MatthewJA** [comment]
here's an excellent template for getting started: https://github.com/navdeep-G/setup.py

@robbibt

**Comment by BexDunn** [comment]
Current plan is to have a subfolder Tools within dea-notebooks which contains setup.py etc
Then it should be synced to the sandbox as per the rest of the repo and perhaps we could pip install it as part of setup...
plan is to register with the dea packages index: https://packages.dea.ga.gov.au/ 

then we can create a similar setup in the africa repo, and a wrapper for some of the functions

**Comment by BexDunn** [comment]
dea-tools is the new branch for this

**Comment by MatthewJA** [comment]
Added the dea-tools module to the dea-tools branch. Testing it out on the notebooks.
