### ISSUE TITLE
Update notebooks that use `pip install --user` instructions

### ISSUE THREAD

**Issue by Kirill888** [GeoscienceAustralia/dea-notebooks#556]
There was a change in the way Python environment is configured in Sandbox. Previously it was not possible to install new packages with user permissions, but it was possible to use `pip --user` mechanism to persistently install extra libraries or update/downgrade existing libs. With the current Sandbox, changes can be made by the user with just `pip install <some lib>` without using `--user` flag, installing with `--user` flag fails. One can also uninstall libs, which was only possible for user installed libraries previously. 

In the new Sandbox, changes made to the Python environment DO NOT persist across reboots. This can be both convenient and annoying depending on the use-case. For testing out new libraries or investigating version compatibilities it's great, but if you have a bunch of extra dependencies or dev installs, these need to be re-installed on every boot. I recommend creating a script or a notebook and running that manually until a better solution is available.

Note that on NCI `--user` flag works and is required on NCI. Sorry for this complication but there is no way to have `pip install` without `--user` flag on NCI, and enabling user installs in Sandbox is also non-trivial/maybe not possible with the current approach (we use `venv` to create user environment that is "independent"-ish from system Python installation)

Quick search turned up following notebooks that use `pip install --user` or ask users to run that. These need to be updated to reflect the new sandbox

https://github.com/GeoscienceAustralia/dea-notebooks/blob/develop/Frequently_used_code/SARA_SLC_download.ipynb @whatnick 

https://github.com/GeoscienceAustralia/dea-notebooks/blob/master/Scientific_workflows/DEAWaterbodies/TurnWaterObservationsIntoWaterbodyPolygons.ipynb @CEKrause @caitlinadams

**Comment by robbibt** [comment]
Thanks @Kirill888 for the update. My personal thought on this is that if a notebook requires custom packages to be installed, it probably belongs on a separate branch rather than in the main automatically synced notebooks (e.g. `Beginners_guide`, `DEA_datasets`, `Frequently_used_code` and `Real_world_examples`).

Ideally, we want to encourage a single, consistent environment without having to trouble-shoot and support custom installs. If a package is useful enough, we should try and get it built into the environment itself rather than recommend users install it on their own.

(Code in the `Scientific_workflows` directory like @CEKrause's above are a different issue and I think are fine, as they aren't intended to be completely reproducible to anyone like the others and contain more complex code that often requires niche packages that aren't necessarily required by all users.)

**Comment by Kirill888** [comment]
Fair enough, I think SARA notebook should probably be moved somewhere else then. I use `Frequently_used_code` directory for testing new sandbox docker images at least in the interim, it's slow can only run in the deployment, and I don't like that, but we don't have better tests right now.

**Comment by robbibt** [comment]
All notebooks using `pip install --user` should be removed from `develop`/`master` now (except for `Scientific workflows` notebooks which are an exception)
