### ISSUE TITLE
BandIndices bug if load_ard product=True

### ISSUE THREAD

**Issue by CEKrause** [GeoscienceAustralia/dea-notebooks#578]
If you use the `load_ard` function and return a `product` variable from the query, this `product` variable causes `dea_bandindices.py` `calculate_indices` function to fail at line 352:
`index_array = index_func(ds.rename(bands_to_rename) / mult)`

The error says it can't perform the operation between a float and a string. I believe it's the `product` sensor strings that are causing the problem, but I can't quite follow through where the issue is actually coming from.

**Comment by robbibt** [comment]
Yeah, it won't like the string variable unfortunately. The easiest workaround is probably to pull out that var, drop it, do the band indices and then add it back. Pseudo code:
```
product_var = ds['product']
out_ds = calculate_indices(ds.drop('product'), ...)
out_ds['product'] = product_var
```

The big update to `load_ard` we have in a PR no longer has the option to generate product metadata strings, so this probably won't be an issue in the future (although it might be good to have `calculate_indices` robust to non-numeric variables).
 
https://github.com/GeoscienceAustralia/dea-notebooks/pull/527

**Comment by CEKrause** [comment]
That is exactly how I have worked around it for now. 

Why are we getting rid of the product strings in `load_ard`?

**Comment by robbibt** [comment]
The new version loads data by first running `dc.find_datasets()` for each of the products, then combining the three lists of datasets into a single list of datasets:

https://github.com/GeoscienceAustralia/dea-notebooks/blob/load_ard_refactor/Scripts/dea_datahandling.py#L284-L303

It then runs `dc.load` once (instead of one per product) by passing in the list of datasets like `dc.load(datasets=dataset_list, ..)`:

https://github.com/GeoscienceAustralia/dea-notebooks/blob/load_ard_refactor/Scripts/dea_datahandling.py#L326-L331

This ends up being a lot more efficient than the current approach of loading the datasets separately then concatenating the results. It also makes the outputs suitable for large-scale dask workflows, as the data is loaded with consistent, nicely aligned dask chunks (in the previous approach, dask chunks weren't always aligned the same between the different `dc.load`ed datasets, so dask operations were many times slower than they needed to be).

However, because multiple products are being loaded in one `dc.load` call, they are no longer associated with a specific, single product. There's also no metadata in the loaded data to determine their sensor, so we aren't able to assign them a label any more.

I'd love to find a solution for this, but I haven't been able to think of one yet

**Comment by robbibt** [comment]
Issue with more details here: https://github.com/GeoscienceAustralia/dea-notebooks/issues/526

**Comment by robbibt** [comment]
`load_ard` no longer has a 'product' parameter; closing this for now
