### ISSUE TITLE
Update DEA_datasets folder to include more dataset notebooks

### ISSUE THREAD

**Issue by MatthewJA** [GeoscienceAustralia/dea-notebooks#615]
The DEA_datasets folder currently only contains notebooks for Sentinel 2 and TSmask. The [archived dataset notebooks](https://github.com/GeoscienceAustralia/dea-notebooks/tree/master_archive/02_DEA_datasets) contain FC, HLTC, ITEM, Landsat, LandsatPQ, Sentinel 2, and WOfS notebooks, which have not yet been ported over.

**Comment by robbibt** [comment]
This has been on our to-do list for a long time, and would be really fantastic to have. Of those notebooks, a rough order of priority would probably be:

1. **Landsat (Collection 3)**
2. **WOfS**
3. **FC**
4. **ITEM (and NIDEM)**
5. **HLTC**

The Landsat notebook should be written for Landsat Collection 3 data (the archived version was based on Collection 2). Because cloud masking data is now a band in the dataset, the **LandsatPQ** notebook is no longer required. There's a very simple starting point for this here (https://github.com/GeoscienceAustralia/dea-notebooks/blob/ls_collection_overview/DEA_datasets/Landsat_collections_quick-guide.ipynb), but it will need to be expanded and cleaned up into a nice consistent format.

**Comment by CEKrause** [comment]
Closed and turned into separate issues instead.
