### ISSUE TITLE
Add a flag to disable Dask for dea_datahandling.load_ard?

### ISSUE THREAD

**Issue by MatthewJA** [GeoscienceAustralia/dea-notebooks#653]
It would be nice to be able to disable Dask for `load_ard`. Note that `dask_chunks=None` is overridden:

```python
    # Note we always load using dask here so that we can lazy load data
    # before filtering by good data
    ds = dc.load(datasets=dataset_list,
                 measurements=measurements,
                 dask_chunks={} if dask_chunks is None else dask_chunks,
                 **kwargs)
```

But sometimes I don't want Dask. In this particular case I know I have enough memory and I want my nice progress bar... I [know this is intentional](https://github.com/GeoscienceAustralia/dea-notebooks/pull/527), which is why an override flag would be good.

**Comment by MatthewJA** [comment]
@robbibt any thoughts?

**Comment by robbibt** [comment]
Yeah, interesting! Just to understand the problem space: does your application use `load_ard` in combination with the `min_gooddata` parameter (e.g. `min_gooddata` set to something greater than 0)?

**Comment by MatthewJA** [comment]
Yeah, it does. The reason I encountered wanting to disable Dask is because with Dask the progress_cbk doesn't work, but I could imagine that there are other scenarios that you'd not want Dask (I don't know what they'd be, because I'm still pretty new to Dask).

My _specific_ issue could be fixed by adding a progress bar, which wouldn't actually be a bad idea either.

**Comment by robbibt** [comment]
Yeah, OK... so I guess the main reason `load_ard` was created was to optimise load times by lazy-loading a time series of data first, load only a single cloud masking band into memory, then only load the remainder of the data for a subset of clear timesteps. This can dramatically improve load times as only a tiny fraction of the data needs to be loaded, rather than the entire time series (i.e. filter by cloud _before_ load, not after)

Without using `dask` to lazy load the time series as the first step, the full time series would always be loaded, regardless of how cloudy the images are. I don't think there's really a technical barrier to disabling this internal use of `dask`, but it would definitely result in much slower load times if used in combination with `min_gooddata`. If `min_gooddata` isn't being used, there probably isn't a reason to use `dask` internally at all, other than internal code simplicity. 

Last time I talked to @Kirill888 about this, I think the conclusion was that progress bars aren't compatible with `dask` at all, so I'm not sure if there's an easy way to do that right now. We usually point people to look at the `dask` progress window whenever they are loading data involving `dask`, although that does require you to keep flicking back and forth to a different tab which isn't ideal...

**Comment by Kirill888** [comment]
Dask version doesn't load data, so no progress inside `.load` is possible, progress bar on `.compute()` inside a jupyterlab notebook is possible, but currently doesn't work in sandbox, requires extra libs or configuration or both.

Dask version of `dc.load` can be quite a bit faster though, especially if you have more cores than the default 2 in sandbox, and choose chunking size well (bigger is more efficient usually). I personally don't use `dc.load` without Dask anymore as it is so painfully slow for anything reasonably sized.

And I use Dask dashboard as "progress bar".

**Comment by MatthewJA** [comment]
Guess we don't need this much then.
