### ISSUE TITLE
interpolate_2d with method = RBF seems to use a lot of memory

### ISSUE THREAD

**Issue by MatthewJA** [GeoscienceAustralia/dea-notebooks#695]
Enough that it crashed my 60 GB pod... This could be a bug.

**Comment by robbibt** [comment]
It could be! If you do narrow anything down I would love to know... it's the main gobbler of memory for DEA Coastlines. How large was your area, or how many points were you interpolating? ( `interpolate_2d` wraps `scipy.interpolate.Rbf`, so that func is probably the bottleneck).

That func also has a `factor` param that can be used to essentially downsample the raster prior to interpolation, and later resample back up to full resolution. That method could help if your application isn't particularly precise (we used it for tide height interpolation as the underlying tidal modelling grid was 2 x 2 km points vs. 30m Landsat pixels)

**Comment by robbibt** [comment]
This is still relevant, but no longer a priority as most of the coastal code is shifting to a reprojection method of resampling low-res data using `odc.geo` (rather than interpolation using RBF)
