### ISSUE TITLE
Unable to open database file

### ISSUE THREAD

**Issue by Daniel-Trung-Nguyen** [GeoscienceAustralia/dea-notebooks#794]
Hi, I'm encountering this error when saving a notebook "The history saving thread hit an unexpected error (OperationalError('unable to open database file',)). History will not be written to the database." This happened after I generated a large notebook (>300 MB)
Can you help advise on the solution?
Many thanks,
Trung
![image](https://user-images.githubusercontent.com/22897462/117926705-84a8d980-b33c-11eb-88cf-fcc2fde07c62.png)

**Comment by Daniel-Trung-Nguyen** [comment]
Just wanting to follow up on this, I believe the problem should be related to the disk quota exceeded on my home directory as it was the message that showed up when I tried to reinstall DEA on the VDI. However, when I checked the storage it showed that I only use 292 MB so far. How do I fix this?

![image](https://user-images.githubusercontent.com/22897462/118053772-71dbe680-b3c8-11eb-82ac-1b372848e491.png)
![image](https://user-images.githubusercontent.com/22897462/118053721-6092da00-b3c8-11eb-8b82-bd23c6fe079e.png)

**Comment by CEKrause** [comment]
Your disk quota on the VDI home directory is very small, which is what's probably causing this issue. I do all my work on the VDI from a directory on /g/data. Do you have a storage location on /g/data you can work from instead of your home directory?

If you don't explicitly need to work from the VDI we also have a parallel environment operating on AWS that you can make use of, which has a small amount of storage associated with it. You wont need to install any systems since the environment is managed. There's information here on how to sign up https://docs.dea.ga.gov.au/setup/sandbox.html

**Comment by Daniel-Trung-Nguyen** [comment]
Thanks @CEKrause! I store all of my inputs and outputs on the /short/ folder. The home directory is only used to store my scripts and notebooks. Everything was working fine until yesterday after I tried to visualize more than 5000 time-series images on a cell output. The notebook crashed stating disk quota exceeded and could not open the database.
Checking my quota (below), it shows that my filesystem block quota is 0 at the moment.
![image](https://user-images.githubusercontent.com/22897462/118055413-68a04900-b3cb-11eb-9aa9-dd8a013eabc4.png)

**Comment by Daniel-Trung-Nguyen** [comment]
It was the error of out of disk storage. Just delete gosh files (.~) files or files stored in the ".ipynb_checkpoints" folder to release disk space
