### ISSUE TITLE
Remove DEA Waterbodies from Scientific workflows and make DEA datasets notebook

### ISSUE THREAD

**Issue by CEKrause** [GeoscienceAustralia/dea-notebooks#806]
DEA Waterbodies has outgrown its life as a folder in `scientific_workflows`. Instead it should be highlighted with a notebook in `DEA_datasets` and the old code removed. 

Make sure to point to the new DEA Waterbodies repo.

* [x] Remove DEA Waterbodies from DEA Notebooks
* [X] Create `DEA_datasets` notebook for Waterbodies

**Comment by robbibt** [comment]
We do have a `DEA_datasets` notebook for Waterbodies, so half of this issue is complete: https://docs.dea.ga.gov.au/notebooks/DEA_datasets/DEA_Waterbodies.html

@CEKrause or @MatthewJA: can I get one of you to do the Waterbodies clean-up in DEA Notebooks next week if you have time? (I'm currently removing all traces of Collection 2-based code from the repo, and at the moment lots of Waterbodies notebooks based on Collection 2 come up in the User Guide tag search)

**Comment by robbibt** [comment]
Done!
