### ISSUE TITLE
Data values of nbart bands

### ISSUE THREAD

**Issue by Daniel-Trung-Nguyen** [GeoscienceAustralia/dea-notebooks#819]
Please excuse my ignorance but can someone quickly explain the data ranges in the NBART bands of the analysis-ready products. I thought the data values are reflectance and should range from 0 - 1. However, the values for nbart_red, nbart_green, nbart_blue loaded from the s2a_ard_granule product seem to range from 100 - 900 and nbart_nir_1 from 1000 to 3000. What are the units of these data and how can I relate them to the reflectance?
Many thanks,
Daniel
![image](https://user-images.githubusercontent.com/22897462/120431159-72f6a700-c3bb-11eb-9d73-2c2a7d545ca1.png)
![image](https://user-images.githubusercontent.com/22897462/120431185-7f7aff80-c3bb-11eb-86b0-7e3788f81c6f.png)

**Comment by robbibt** [comment]
Hi @Daniel-Trung-Nguyen, the values are surface reflectance scaled between 0 and 10,000. This is simply because it's more efficient to store the values as integers than floating point values between 0.0 and 1.0. You can convert them to more typical surface reflectance values by dividing them by 10,000 (although this may not always be necessary, and will require more memory than leaving them as integers. You will however need to do it before calculating things like certain band indices which assume values are between 0.0-1.0).

**Comment by Daniel-Trung-Nguyen** [comment]
Hi @robbibt,  thanks for the very quick response! It makes sense to me now. I think that should be mentioned in the documents somewhere, if not it is a good idea to include.
A related question that I have and can't seem to find the answer anywhere, DEA products make it easy to pull data and create time series from a combination of ARD Landsat 5, 7, 8, and Sentinel 2. I know that all the data have gone through NBART correction, but I am not sure if any adjustments have been made to correct for biases from different sensors and their spectral ranges. In other words, do I need to correct for the sensor differences when fusing the data from different sources or it is not necessary? 
If I provide a list of products to the dc.load() or dc.load_ard(), is there an option to know which scenes come from which product on the returned xarray dataset?
Many thanks,
Daniel

**Comment by robbibt** [comment]
> I think that should be mentioned in the documents somewhere, if not it is a good idea to include.

Hey @Daniel-Trung-Nguyen , I agree about documenting the /10,000 transformation, if you get a chance could you raise a Github issue suggesting that we explain that in the documentation?

> A related question that I have and can't seem to find the answer anywhere, DEA products make it easy to pull data and create time series from a combination of ARD Landsat 5, 7, 8, and Sentinel 2. I know that all the data have gone through NBART correction, but I am not sure if any adjustments have been made to correct for biases from different sensors and their spectral ranges. In other words, do I need to correct for the sensor differences when fusing the data from different sources or it is not necessary?

The simple answer is that no, there are no transforms applied to adjust for sensor-specific biases. It will be up to your own use case whether you can combine the multiple sensors into a single time series - the differences can be negligible for some applications and more important for others (e.g. for some of our coastal applications we've found that the accuracy of shoreline extraction does not vary significantly by sensor). 

> If I provide a list of products to the dc.load() or dc.load_ard(), is there an option to know which scenes come from which product on the returned xarray dataset?

Only `load_ard` actually supports multiple products - `dc.load` will still work when multiple products are passed, but it's not intended functionality and will be removed in future versions. For the product metadata, we used to have this functionality but unfortunately it's not possible now due to the way that `load_ard` loads data (it identifies all of the individual raster datasets from all of the products and loads them together, which is much more efficient than looping through the products one by one, but means there's no ability to assign each time step with a unique label). Your best bet would be to load the products one by one with either `load_ard` or `dc.load`, then assign them with an attribute using [assign_attrs](http://xarray.pydata.org/en/stable/generated/xarray.DataArray.assign_attrs.html), then concatenate into a single `xarray`.

**Comment by Daniel-Trung-Nguyen** [comment]
@robbibt, thanks a lot for the answer. It sheds light on stuff that I was trying to understand going through the documentation. I'll raise an issue suggesting the /10,000 transformations.
Cheers,
Daniel
