### ISSUE TITLE
question

### ISSUE THREAD

**Issue by leaf0917** [GeoscienceAustralia/dea-notebooks#881]
Is the scene in DEA all processed ard data? If yes, which software is generally used for processing? And can the original images downloaded from usgs be imported into dea?

**Comment by robbibt** [comment]
Hi @leaf0917, there's lots of information about how the DEA ARD datasets are processed here: 
https://cmi.ga.gov.au/data-products/dea/365/dea-surface-reflectance-landsat-8-oli-tirs#basics

There are USGS products available on the DEA Sandbox, but they are not available systematically (only for certain locations):

https://explorer.sandbox.dea.ga.gov.au/products/ls8_usgs_l2c1/extents
https://explorer.sandbox.dea.ga.gov.au/products/ls7_usgs_l2c1/extents
https://explorer.sandbox.dea.ga.gov.au/products/ls5_usgs_l2c1/extents

**Comment by leaf0917** [comment]
> Hi @leaf0917, there's lots of information about how the DEA ARD datasets are processed here: https://cmi.ga.gov.au/data-products/dea/365/dea-surface-reflectance-landsat-8-oli-tirs#basics
> 
> There are USGS products available on the DEA Sandbox, but they are not available systematically (only for certain locations):
> 
> https://explorer.sandbox.dea.ga.gov.au/products/ls8_usgs_l2c1/extents https://explorer.sandbox.dea.ga.gov.au/products/ls7_usgs_l2c1/extents https://explorer.sandbox.dea.ga.gov.au/products/ls5_usgs_l2c1/extents

The processing of ARD data seems very complicated. Can I download USGS product and import it into DEA, and use it directly without ARD processing?

**Comment by BexDunn** [comment]
Hey @leaf0917 if you are looking to use the opendatacube with downloaded USGS data, you might want to investigate the Open Data Cube project documentation. DEA is an implementation of the Open Data Cube for Australia, and you might like to 'build your own cube'? https://datacube-core.readthedocs.io/en/latest/  . Otherwise you can certainly download your own copies of USGS data or access them programmatically and use them with DEA data, but you will find that you may need to extensively rewrite some of the code in this repository  for those uses as some of the variables will be explicitly set for the DEA naming conventions etc. The ARD processing has significant advantage for the Australian data, and having access to the ready-processed Analysis Ready Data through DEA basically means you don't have to process it yourself. Can I ask what you're trying to do? I might be able to give you better advice!

**Comment by leaf0917** [comment]
> Hey @leaf0917 if you are looking to use the opendatacube with downloaded USGS data, you might want to investigate the Open Data Cube project documentation. DEA is an implementation of the Open Data Cube for Australia, and you might like to 'build your own cube'? https://datacube-core.readthedocs.io/en/latest/ . Otherwise you can certainly download your own copies of USGS data or access them programmatically and use them with DEA data, but you will find that you may need to extensively rewrite some of the code in this repository for those uses as some of the variables will be explicitly set for the DEA naming conventions etc. The ARD processing has significant advantage for the Australian data, and having access to the ready-processed Analysis Ready Data through DEA basically means you don't have to process it yourself. Can I ask what you're trying to do? I might be able to give you better advice!

Thank you for your reply. I'm just interested in ODC. I don't have any specific ideas. If so, I'll consult you in detail！
